development:
  adapter: postgresql
  encoding: unicode
  database: games_v2_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: games_v2_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: games_v2_production
  pool: 5
  username:
  password:
