Word.create!(body: 'basketball')
Word.create!(body: 'greg')
Word.create!(body: 'chair')
Word.create!(body: 'subway')
Word.create!(body: 'academy')
Word.create!(body: 'programming')
Word.create!(body: 'hello')
